### ISSUE TITLE
StyleGAN3 CPU

### ISSUE THREAD

**Issue by RahulBhalley** [senior-sigan/rosinality-stylegan2-pytorch-cpu#1]
Hi! Thanks for your work. Do you have implementation of StyleGAN3 ops in CPU? If so, do you have any plans to release it? 

I am talking about this [torch_utils/ops](https://github.com/NVlabs/stylegan3/tree/main/torch_utils/ops).

Regards
Rahul Bhalley

**Comment by senior-sigan** [comment]
Hello, @RahulBhalley .
Unfortunately, I don't have any plans on updating this repo.
I hope you'll find a solution. Sorry.

Thanks.

**Comment by RahulBhalley** [comment]
It's okay. Thanks for open sourcing this work. 😄
